from textual.app import App, ComposeResult
from textual.widgets import Header, Footer, Static
from textual.reactive import reactive
from textual.binding import Binding

# --- DUMMY DATA ---
# Each dictionary represents the state at a particular step.
# In the real app, this will be generated by querying storage.py:
# `events = get_state_at(conn, current_step)`
# and then mapped to UI data.
# The 'line' field tells the CodeView which line is active.
DUMMY_TRACE = [
    {"step": 0, "line": 1, "vars": {}},
    {"step": 1, "line": 2, "vars": {"x": "10"}},
    {"step": 2, "line": 3, "vars": {"x": "10", "y": "20"}},
    {"step": 3, "line": 4, "vars": {"x": "30", "y": "20"}},
    {"step": 4, "line": 5, "vars": {"x": "30", "y": "20", "z": "50"}},
]

DUMMY_CODE = """\
def calculate():
    x = 10
    y = 20
    x = x + y
    z = x + y
    return z
""".splitlines()

class CodeView(Static):
    """Left pane for displaying code with the active line highlighted."""
    
    active_line = reactive(0)
    
    def render(self) -> str:
        lines = []
        for i, line in enumerate(DUMMY_CODE, start=1):
            if i == self.active_line:
                # Highlight the active line with a marker and reverse video
                lines.append(f"[reverse]▶ {i:3} | {line}[/reverse]")
            else:
                lines.append(f"  {i:3} | {line}")
        return "\n".join(lines)

class TimelineView(Static):
    """Right pane for displaying scrub bar, step info, and variables."""
    
    current_step = reactive(0)
    max_step = reactive(0)
    active_line = reactive(0)
    variables = reactive({})
    
    def render(self) -> str:
        # Scrub bar: [────●─────]
        bar_length = 20
        if self.max_step > 0:
            pos = int((self.current_step / self.max_step) * (bar_length - 1))
        else:
            pos = 0
            
        bar_chars = ["─"] * bar_length
        if 0 <= pos < bar_length:
            bar_chars[pos] = "●"
        scrub_bar = f"[{''.join(bar_chars)}]"
        
        output = [
            "[bold]Timeline[/bold]",
            f"{scrub_bar}",
            f"Step: {self.current_step} / {self.max_step}",
            f"Line: {self.active_line}",
            "",
            "[bold]Variables:[/bold]"
        ]
        
        if not self.variables:
            output.append("  (none)")
        else:
            for k, v in self.variables.items():
                output.append(f"  {k} = {v}")
                
        return "\n".join(output)

class PyChronicleApp(App):
    """Main Textual application for PyChronicle time-travel debugger."""
    
    # CSS block assigning proportions and borders to the two panes
    CSS = """
    Screen {
        layout: horizontal;
    }
    CodeView {
        width: 2fr;
        height: 100%;
        border: solid green;
        padding: 1 2;
    }
    TimelineView {
        width: 1fr;
        height: 100%;
        border: solid blue;
        padding: 1 2;
    }
    """
    
    BINDINGS = [
        Binding("left", "step_back", "Step Back"),
        Binding("right", "step_forward", "Step Forward"),
        Binding("home", "step_first", "First Step"),
        Binding("end", "step_last", "Last Step"),
        Binding("q", "quit", "Quit"),
    ]
    
    # Single source of truth for the step
    current_step = reactive(0)
    
    def compose(self) -> ComposeResult:
        yield Header()
        yield CodeView(id="code_view")
        yield TimelineView(id="timeline_view")
        yield Footer()
        
    def on_mount(self) -> None:
        self.max_step = len(DUMMY_TRACE) - 1
        self.update_panes()
        
    def watch_current_step(self, old_step: int, new_step: int) -> None:
        """Triggered automatically whenever current_step changes."""
        self.update_panes()
        
    def update_panes(self) -> None:
        """Syncs the child panes with the current step's data."""
        # --- SWAP-IN POINT FOR SQLITE ---
        # When integrating with storage.py, you would do something like:
        # events = get_state_at(conn, self.current_step)
        # variables = {row[5]: row[6] for row in events} # variable_name -> variable_value
        # active_line = ... (you might need to fetch the active line from a different query or logic)
        
        trace_data = DUMMY_TRACE[self.current_step]
        active_line = trace_data["line"]
        variables = trace_data["vars"]
        
        # Update CodeView
        code_view = self.query_one(CodeView)
        code_view.active_line = active_line
        
        # Update TimelineView
        timeline = self.query_one(TimelineView)
        timeline.current_step = self.current_step
        timeline.max_step = self.max_step
        timeline.active_line = active_line
        timeline.variables = variables

    def action_step_back(self) -> None:
        """Move back one step in time."""
        if self.current_step > 0:
            self.current_step -= 1

    def action_step_forward(self) -> None:
        """Move forward one step in time."""
        if self.current_step < self.max_step:
            self.current_step += 1

    def action_step_first(self) -> None:
        """Jump to the very beginning."""
        self.current_step = 0
        
    def action_step_last(self) -> None:
        """Jump to the end."""
        self.current_step = self.max_step

if __name__ == "__main__":
    app = PyChronicleApp()
    app.run()
